// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.4
// source: photo_frame.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetGridReq_OldImageAction int32

const (
	SetGridReq_OLD_IMAGE_KEEP SetGridReq_OldImageAction = 0 // keep old images on a new grid
	SetGridReq_OLD_IMAGE_WIPE SetGridReq_OldImageAction = 1 // remove old images from the grid
	SetGridReq_OLD_IMAGE_FADE SetGridReq_OldImageAction = 2 // fade old images on a new grid
)

// Enum value maps for SetGridReq_OldImageAction.
var (
	SetGridReq_OldImageAction_name = map[int32]string{
		0: "OLD_IMAGE_KEEP",
		1: "OLD_IMAGE_WIPE",
		2: "OLD_IMAGE_FADE",
	}
	SetGridReq_OldImageAction_value = map[string]int32{
		"OLD_IMAGE_KEEP": 0,
		"OLD_IMAGE_WIPE": 1,
		"OLD_IMAGE_FADE": 2,
	}
)

func (x SetGridReq_OldImageAction) Enum() *SetGridReq_OldImageAction {
	p := new(SetGridReq_OldImageAction)
	*p = x
	return p
}

func (x SetGridReq_OldImageAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetGridReq_OldImageAction) Descriptor() protoreflect.EnumDescriptor {
	return file_photo_frame_proto_enumTypes[0].Descriptor()
}

func (SetGridReq_OldImageAction) Type() protoreflect.EnumType {
	return &file_photo_frame_proto_enumTypes[0]
}

func (x SetGridReq_OldImageAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetGridReq_OldImageAction.Descriptor instead.
func (SetGridReq_OldImageAction) EnumDescriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{1, 0}
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Types that are assignable to Image:
	//
	//	*Image_Rgb8
	//	*Image_Rgba8
	//	*Image_Png
	//	*Image_Jpeg
	Image isImage_Image `protobuf_oneof:"image"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photo_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_photo_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (m *Image) GetImage() isImage_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (x *Image) GetRgb8() []byte {
	if x, ok := x.GetImage().(*Image_Rgb8); ok {
		return x.Rgb8
	}
	return nil
}

func (x *Image) GetRgba8() []byte {
	if x, ok := x.GetImage().(*Image_Rgba8); ok {
		return x.Rgba8
	}
	return nil
}

func (x *Image) GetPng() []byte {
	if x, ok := x.GetImage().(*Image_Png); ok {
		return x.Png
	}
	return nil
}

func (x *Image) GetJpeg() []byte {
	if x, ok := x.GetImage().(*Image_Jpeg); ok {
		return x.Jpeg
	}
	return nil
}

type isImage_Image interface {
	isImage_Image()
}

type Image_Rgb8 struct {
	Rgb8 []byte `protobuf:"bytes,3,opt,name=rgb8,proto3,oneof"` // 8 bit per channel RGB
}

type Image_Rgba8 struct {
	Rgba8 []byte `protobuf:"bytes,4,opt,name=rgba8,proto3,oneof"` // 8 bit per channel RGBA
}

type Image_Png struct {
	Png []byte `protobuf:"bytes,5,opt,name=png,proto3,oneof"` // PNG bytes
}

type Image_Jpeg struct {
	Jpeg []byte `protobuf:"bytes,6,opt,name=jpeg,proto3,oneof"` // JPEG bytes
}

func (*Image_Rgb8) isImage_Image() {}

func (*Image_Rgba8) isImage_Image() {}

func (*Image_Png) isImage_Image() {}

func (*Image_Jpeg) isImage_Image() {}

type SetGridReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cols        uint32                    `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows        uint32                    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	OldImageAct SetGridReq_OldImageAction `protobuf:"varint,3,opt,name=old_image_act,json=oldImageAct,proto3,enum=protocol.SetGridReq_OldImageAction" json:"old_image_act,omitempty"`
	Images      []*Image                  `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"` // if set, should be exactly rows * cols
}

func (x *SetGridReq) Reset() {
	*x = SetGridReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photo_frame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGridReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGridReq) ProtoMessage() {}

func (x *SetGridReq) ProtoReflect() protoreflect.Message {
	mi := &file_photo_frame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGridReq.ProtoReflect.Descriptor instead.
func (*SetGridReq) Descriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{1}
}

func (x *SetGridReq) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SetGridReq) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *SetGridReq) GetOldImageAct() SetGridReq_OldImageAction {
	if x != nil {
		return x.OldImageAct
	}
	return SetGridReq_OLD_IMAGE_KEEP
}

func (x *SetGridReq) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type SetGridResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetGridResp) Reset() {
	*x = SetGridResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photo_frame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGridResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGridResp) ProtoMessage() {}

func (x *SetGridResp) ProtoReflect() protoreflect.Message {
	mi := &file_photo_frame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGridResp.ProtoReflect.Descriptor instead.
func (*SetGridResp) Descriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{2}
}

type AddImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *AddImageReq) Reset() {
	*x = AddImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photo_frame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageReq) ProtoMessage() {}

func (x *AddImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_photo_frame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageReq.ProtoReflect.Descriptor instead.
func (*AddImageReq) Descriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{3}
}

func (x *AddImageReq) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type AddImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddImageResp) Reset() {
	*x = AddImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photo_frame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageResp) ProtoMessage() {}

func (x *AddImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_photo_frame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageResp.ProtoReflect.Descriptor instead.
func (*AddImageResp) Descriptor() ([]byte, []int) {
	return file_photo_frame_proto_rawDescGZIP(), []int{4}
}

var File_photo_frame_proto protoreflect.FileDescriptor

var file_photo_frame_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x96, 0x01,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x72, 0x67, 0x62, 0x38, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x72, 0x67, 0x62, 0x38, 0x12, 0x16, 0x0a, 0x05, 0x72,
	0x67, 0x62, 0x61, 0x38, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x72, 0x67,
	0x62, 0x61, 0x38, 0x12, 0x12, 0x0a, 0x03, 0x70, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x03, 0x70, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x6a, 0x70, 0x65, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x70, 0x65, 0x67, 0x42, 0x07, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x47, 0x72,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x47, 0x0a,
	0x0d, 0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x53, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x52, 0x65, 0x71, 0x2e, 0x4f, 0x6c, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x4c, 0x0a, 0x0e, 0x4f, 0x6c, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x4c, 0x44, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x4b,
	0x45, 0x45, 0x50, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x4c, 0x44, 0x5f, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x5f, 0x57, 0x49, 0x50, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x4c, 0x44,
	0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x46, 0x41, 0x44, 0x45, 0x10, 0x02, 0x22, 0x0d, 0x0a,
	0x0b, 0x53, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x36, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x32, 0x7f, 0x0a, 0x0a, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53,
	0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6e, 0x6e, 0x77, 0x63, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x2d, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_photo_frame_proto_rawDescOnce sync.Once
	file_photo_frame_proto_rawDescData = file_photo_frame_proto_rawDesc
)

func file_photo_frame_proto_rawDescGZIP() []byte {
	file_photo_frame_proto_rawDescOnce.Do(func() {
		file_photo_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_photo_frame_proto_rawDescData)
	})
	return file_photo_frame_proto_rawDescData
}

var file_photo_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_photo_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_photo_frame_proto_goTypes = []interface{}{
	(SetGridReq_OldImageAction)(0), // 0: protocol.SetGridReq.OldImageAction
	(*Image)(nil),                  // 1: protocol.Image
	(*SetGridReq)(nil),             // 2: protocol.SetGridReq
	(*SetGridResp)(nil),            // 3: protocol.SetGridResp
	(*AddImageReq)(nil),            // 4: protocol.AddImageReq
	(*AddImageResp)(nil),           // 5: protocol.AddImageResp
}
var file_photo_frame_proto_depIdxs = []int32{
	0, // 0: protocol.SetGridReq.old_image_act:type_name -> protocol.SetGridReq.OldImageAction
	1, // 1: protocol.SetGridReq.images:type_name -> protocol.Image
	1, // 2: protocol.AddImageReq.images:type_name -> protocol.Image
	2, // 3: protocol.PhotoFrame.SetGrid:input_type -> protocol.SetGridReq
	4, // 4: protocol.PhotoFrame.AddImage:input_type -> protocol.AddImageReq
	3, // 5: protocol.PhotoFrame.SetGrid:output_type -> protocol.SetGridResp
	5, // 6: protocol.PhotoFrame.AddImage:output_type -> protocol.AddImageResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_photo_frame_proto_init() }
func file_photo_frame_proto_init() {
	if File_photo_frame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_photo_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photo_frame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGridReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photo_frame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGridResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photo_frame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photo_frame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_photo_frame_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Image_Rgb8)(nil),
		(*Image_Rgba8)(nil),
		(*Image_Png)(nil),
		(*Image_Jpeg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_photo_frame_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_photo_frame_proto_goTypes,
		DependencyIndexes: file_photo_frame_proto_depIdxs,
		EnumInfos:         file_photo_frame_proto_enumTypes,
		MessageInfos:      file_photo_frame_proto_msgTypes,
	}.Build()
	File_photo_frame_proto = out.File
	file_photo_frame_proto_rawDesc = nil
	file_photo_frame_proto_goTypes = nil
	file_photo_frame_proto_depIdxs = nil
}
